/*
 * signalGenerator.c
 *
 *  Created on: Mar 22, 2026
 *      Author: bozhi
 */

#include <stdio.h>
#include <string.h>
#include <math.h>

#include "menu_config.h"
#include "signalGen.h"
#include "menu_simulation.h"
#include "dac.h"
#include "pwm.h"
#include "display.h"
#include "io.h"
#include "tim.h"

static void generateSineWave(char type);
static void genTriangleWave(char type);
static void genSawToothWave(char type);

uint16_t sine_table[N_SAMPLES];

static unsigned char simulation_state = 0;

char *func_array[]  = { "Sine",  "Square","Triang" };
char *burst_array[] = { "None",  "Time",  "Pulse"  };
char *wave_array[]  = { "NORMAL", "FULL-RECT"      };

/*
SignalGenCfg signal_cfg[] = {

	FUNC_TYPE_SINE,     generateSineWave,
	FUNC_TYPE_TRIANGLE, genTriangleWave
};
*/

/*
  unsigned long sys_clock = HAL_RCC_GetSysClockFreq();
  unsigned int tim1 = HAL_RCC_GetPCLK2Freq();

  printf("SYSCLK: %lu\n", HAL_RCC_GetSysClockFreq());
  printf("HCLK  : %lu\n", HAL_RCC_GetHCLKFreq());
  printf("PCLK1 : %lu\n", HAL_RCC_GetPCLK1Freq());*/

//DAC_Write(2047); // Send a constant impulse of 2048(out of 4095) to the DAC chanel

void initSignalGen(void){

	setEncoderVal(1);
	generateSignalTable();
}

char* getFuncName(int func_id){
	return func_array[func_id];
}

int getFuncTabSize(void){
	return sizeof(func_array) / sizeof(func_array[0]);
}

char* getWaveType(int wave_type){
	return wave_array[wave_type];
}

int getWaveTabSize(void){
	return sizeof(wave_array) / sizeof(wave_array[0]);
}

char* getBurstType(int burst_type){
	return burst_array[burst_type];
}

int getBurstTabSize(void){
	return sizeof(burst_array) / sizeof(burst_array[0]);
}

unsigned char getSimulationState(void){
	return simulation_state;
}

unsigned char getDutyCycle(void){

	CONFIG_STRUCT cfg = getConfigStruct();
	return cfg.duty_cycle;
}

/*
 * Read the encoder and return its value in Hz.
 * The default frequency value is 1000Hz
 * */
unsigned int getCurrentFrequency(void){

	unsigned int enc_data = getEncoderVal();

	if(enc_data == 0){
		enc_data++;
	}
	enc_data*=1000;

	return enc_data;
}

/**
 * Toggle the DAC channel. When the channel is ON, a sine wave signal(or another type)
 * is send to the output pin with a frequency defined by the rotary encoder.
 * The current frequency will be shown on the display.
 * */
void toggleSignalGenerator(void){

	CONFIG_STRUCT cfg = getConfigStruct();

	//Start simulation
	if(simulation_state == 0){

		simulation_state = 1;
		enableEncoder(0);
		dispCurrentFreq();

		//Start PWM generator
		if(cfg.func_type == FUNC_TYPE_SQUARE){
			StartPWM(getCurrentFrequency(), cfg.duty_cycle);
		}
		else{ //Start the analog signal generator: sine, triangle, etc.

			//For a full-rectified signal, the frequency must be divided by 2
			unsigned int freq = getCurrentFrequency();
			if(cfg.wave_type == SIGNAL_TYPE_FULL_RECT){
				freq/=2;
			}
			startDAC(sine_table, N_SAMPLES, freq);
		}
	}
	else{//Stop the simulation
		simulation_state = 0;
		enableEncoder(1);
		dispCurrentFreq();

		if(cfg.func_type == FUNC_TYPE_SQUARE){
			stopPWM();
		}
		else{
			toggleDAC(0);
		}
	}
}

/**
 * Signal generator dispatcher.
 * If an analog function type is selected(sine, triangle, sawtooth, etc),
 * a single period of the corresponding wave will be generated and stored to a buffer.
 * Later, this buffer will be used by the DAC to generate the output signal.
**/
void generateSignalTable(void){

	CONFIG_STRUCT cfg = getConfigStruct();

	if(cfg.func_type == FUNC_TYPE_SINE){
		generateSineWave(cfg.wave_type);
	}
	else if(cfg.func_type == FUNC_TYPE_TRIANGLE){
		genTriangleWave(cfg.wave_type);
	}
	else if(cfg.func_type == FUNC_TYPE_SAW){
		genSawToothWave(cfg.wave_type);
	}
	else if(cfg.func_type == FUNC_TYPE_SQUARE){

		//NOTE: No need to generate any signal since the PWM is generated by the PWM channel.
		//May be set some function properties such as duty cycle
		//StartPWM(1000, 50);
	}
}

/******************************* The signal functions are defined below ***********************************/

/** Three types of wave might be generated:
 *
 *  Param:
 *  - Type: The wave rectification type.
 *
 *  - 0: No rectification
 *  - 1: Half rectified
 *  - 2: Full rectified
 * */
static void generateSineWave(char type){

	memset(sine_table, 0, sizeof sine_table);

	//Pure sine wave:
	if(type == SIGNAL_TYPE_NORMAL){

		int offset   = AMPLITUDE/2;
		int temp_amp = offset;

		for (int i = 0; i < N_SAMPLES; i++){
		    sine_table[i] = (uint16_t)(offset + temp_amp * sinf(2.0f * M_PI * i / N_SAMPLES));
		}
	}
	else if(type == SIGNAL_TYPE_FULL_RECT){

	    for (int i = 0; i < N_SAMPLES; i++){

	        float s = sinf(2.0f * M_PI * i / N_SAMPLES);
	        if (s < 0.0f){
	            s = -s;   // Positive values only
	        }
	        sine_table[i] = (uint16_t)(4095.0f * s);
	    }
	}
	else if(type == SIGNAL_TYPE_HALF_RECT){

		//TODO: IMPLEMENT!!!!
		//Half-rectified - WON'T BE USED FOR NOW
	}
}

/** - You can generate a basic triangular wave.
 *  - A half-rectified.
 *  - Or a saw-tooth wave type.
 *
 *  @Param:
 *  - Type: The rectification type.
 *  - 0: No rectification.
 *  - 1: Half rectified.
 *  - 2: Full rectified.
 * */
static void genTriangleWave(char type){

	if(type == SIGNAL_TYPE_NORMAL){ //Normal wave. No rectification

		int pos=0;
		for(int i = 0; i < N_SAMPLES/2; i++){
			sine_table[pos++] = 2*(AMPLITUDE * i)/100; //Reach max amplitude of 3.6v
		}
		for(int i = N_SAMPLES/2; i > 0; i--){
			sine_table[pos++] = 2*(AMPLITUDE * i)/100;
		}
	}
	else if(type == SIGNAL_TYPE_HALF_RECT){//Half-rectified - WON'T BE USED FOR NOW

	}
	else if(type == SIGNAL_TYPE_FULL_RECT){ //Full wave rectification

	}
}

static void genSawToothWave(char type){

	/*
	 //SAWTOOTH WAVE
	 uint32_t value = (2UL * AMPLITUDE * i) / N_SAMPLES-value;

	if(value > AMPLITUDE){
		value =0; //2 * AMPLITUDE - value;
	}
	triangle_table[i] = (uint16_t)value;*/

	/*
    if (i < N_SAMPLES/2){
    	triangle_table[i] = (2.0f * i / N_SAMPLES) * AMPLITUDE;
    }
    else{
    	triangle_table[i] = (2.0f - (2.0f * i / N_SAMPLES)) * AMPLITUDE;
    }*/
}


